name: CI
##
# Add the line below to README.md and the badge will come alive when the repo is public.
# [![CI](https://github.com/monarch-initiative/C2S2/workflows/CI/badge.svg)](https://github.com/monarch-initiative/C2S2/actions/workflows/python_ci.yml)

on:
    push:
      # Uncomment when we have `development` and remove `main`
#      branches: [ development ]
      branches: [ main ]
    pull_request:
      # Uncomment when we have `development`
#      branches: [ main, development ]
      branches: [ main ]

jobs:
    build:
      runs-on: ${{ matrix.os }}

      strategy:
        fail-fast: false
        matrix:
          os: [  ubuntu-latest ]
          python: [ "3.9" ]

      steps:
        - uses: actions/checkout@v2
        - name: Initialize Python ${{ matrix.python }}
          uses: actions/setup-python@v1
          with:
            python-version: ${{ matrix.python }}
        - name: Install package
          run: |
            python -m pip install --upgrade pip
            pip install .
        - name: Run tests
          run: |
            python -m unittest discover -s phenoscore
